ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('payments/', include('payment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth

app_name = 'shop'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('shop/<int:page>', views.shop, name='shop'),
    path('shop/<name>/<int:page>/', views.shop_cat, name='shop-cat'),
    path('company/<int:id>/<int:page>/', views.company_shop, name='company-shop'),
    path('product/<int:id>/', views.product, name='product'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove-from-cart'),
    path('reduce-order-quantity/<int:id>/', views.reduce_order_quantity, name='reduce-order-quantity'),
    path('cart/', views.order_summary, name='cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('accounts/login/', views.login_view, name='login_page'),
    path('register/', views.register_view, name='register_page'),
    path('logout/', views.logout_view, name='logout')
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django_countries.fields import CountryField

# Create your models here.

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Company(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='company')
    name = models.CharField(max_length=200)
    cover_photo = models.ImageField(upload_to='company_cover')
    about = models.TextField()

    def __str__(self):
        return self.name

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='products', null=True, blank=True)
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    price = models.DecimalField(decimal_places=2, max_digits=20)
    desc = models.TextField()
    photo = models.ImageField(upload_to='products')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=1, choices=STATUS)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_on']

    def get_absolute_url(self):
        return reverse("shop:product", kwargs={"id": self.id})
    
    def get_add_to_cart_url(self):
        return reverse("shop:add-to-cart", kwargs={"id": self.id})
    
    def get_remove_from_cart_url(self):
        return reverse("shop:remove-from-cart", kwargs={"id": self.id})
    
    def get_reduce_order_quantity_url(self):
        return reverse("shop:reduce-order-quantity", kwargs={"id": self.id})

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"
    
    def get_total_price(self):
        return self.quantity * self.product.price
    
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    class Meta:
        ordering = ['-start_date']

    def __str__(self):
        return f"{self.user.username}"
    
    def get_total_price(self):
        total = 0
        for product in self.products.all():
            total += product.get_total_price()
        return total
    
class Checkout(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='checkout')
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(blank=True, max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username
    
class ProductReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_reviews')
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} comment on {self.product}"
    
    class Meta:
        ordering = ['-created_on']

    

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length=20)
    address = forms.CharField(max_length=100)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ['username', 'email', 'phone_no', 'address', 'first_name', 'last_name', 'password1', 'password2']


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mt-3 ps-3 mb-3',
        'placeholder': '1234 Main Str'
    }))

    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control ps-3 mb-4',
        'placeholder': 'Apartment or suite'
    }))

    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'form-select form-control mt-2 mb-4'
    }))

    city = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mt-3 ps-3 mb-4',
        'placeholder': 'Town/City'
    }))

    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control mt-2 mb-4 ps-3'
    }))

shop/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Product, Category, OrderItem, Order, Checkout, Company, ProductReview
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserRegisterForm, CheckoutForm
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from payment.models import Payment
from django.db.models import Q

# Create your views here.


def home_page(request):

    categories = Category.objects.all()

    if categories:

        for cat in categories:
            cat_products = Product.objects.filter(category=cat)[:4]
            categories.products = cat_products

    companies = Company.objects.all()

    return render(request, 'index.html', {'categories': categories,
                                          'companies': companies})

def shop(request, page):
    search_field = request.GET.get('search')

    if search_field:
        products = Product.objects.filter(Q(name__icontains=search_field))
        
    else:
        products = Product.objects.all()

    companies = Company.objects.all()
    categories = Category.objects.all()
    pag_products = Paginator(products, per_page=9)
    products = pag_products.get_page(page)

    return render(request, 'shop.html', {'products': products,
                                         'categories': categories,
                                         'companies': companies,
                                         'search': search_field})

def shop_cat(request, name, page):
    categories = Category.objects.all()
    category = get_object_or_404(Category, name=name)
    products = Product.objects.filter(category=category)
    pag_products = Paginator(products, per_page=9)
    products = pag_products.get_page(page)

    return render(request, 'shop_cat.html', {'products': products,
                                             'category': category,
                                             'categories': categories})

def company_shop(request, id, page):
    company = get_object_or_404(Company, id=id)
    user = company.user
    products = Product.objects.filter(user=user)
    pag_products = Paginator(products, per_page=9)
    products = pag_products.get_page(page)
    categories = Category.objects.all()

    return render(request, 'company_shop.html', {'products': products,
                                                 'categories': categories,
                                                 'company': company
                                                 })

def product(request, id):
    product = get_object_or_404(Product, id=id)

    if request.method == "POST":
        comment = request.POST["comment"]
        new_review = ProductReview.objects.create(
            user = request.user,
            comment=comment,
            product=product
        )
        new_review.save()
        messages.success(request, "your review has been added")

    categories = Category.objects.all()
    order_quantity = 0

    category = product.category
    related_products = Product.objects.filter(category=category)[:4]
    reviews = ProductReview.objects.filter(product=product)

    try:
        order_qs = Order.objects.filter(user=request.user, ordered=False)

        if order_qs.exists():
            order = order_qs[0]

            if order.products.filter(product_id=id).exists():
                order = OrderItem.objects.filter(user=request.user, ordered=False, product=product)[0]
                order_quantity = order.quantity
            
            else:
                order_quantity = 0
        
        else:
            order_quantity = 0

    except ObjectDoesNotExist:
        order = False


    return render(request, 'product.html', {'product': product,
                                            'related_products': related_products,
                                            'order_qty': order_quantity,
                                            'categories': categories,
                                            'reviews': reviews
                                            })


def login_view(request):
    categories = Category.objects.all()
    if request.method == "POST":

        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            form = login(request, user)
            messages.success(request, f"Welcome {username}!")
            return redirect('shop:home')
        
        else:
            messages.info(request, "Account does not exist please sign in")

    form = AuthenticationForm()
    return render(request, 'login.html', {'form': form,
                                          'categories': categories})

def register_view(request):
    categories = Category.objects.all()
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration Successful!")
            return redirect("shop:home")
        else:
            messages.info(request, "Please make sure to fill the details in correctly")
    
    else:
        form = UserRegisterForm()

    return render(request, 'register.html', {'form': form,
                                             'categories': categories})


@login_required
def logout_view(request):

    logout(request)
    return redirect("shop:login_page")
    
@login_required
def add_to_cart(request, id):
    product = get_object_or_404(Product, id=id)
    order_item, created = OrderItem.objects.get_or_create(
        product = product,
        user = request.user,
        ordered = False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.products.filter(product_id = product.id).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Added product quantity successfully")
            return redirect("shop:product", id=id)
        
        else:
            order.products.add(order_item)
            messages.info(request, "Product added to cart succesfully")
            return redirect("shop:product", id=id)
        
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user = request.user,
            ordered_date = ordered_date
        )
        order.products.add(order_item)
        messages.info(request, "Product added to cart successfully")
        return redirect("shop:product", id=id)
    
@login_required
def reduce_order_quantity(request, id):
    product = get_object_or_404(Product, id=id)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product_id=id).exists():
            order_item =  OrderItem.objects.filter(user=request.user, ordered=False, product=product)[0]

            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            
            else:
                order_item.delete()

            messages.info(request, "Order item quantity updated!")
            return redirect("shop:cart")
        
        else:
            messages.info(request, "Product is not in your cart")
            return redirect("shop:product", id=id)
    
    else:

        messages.info(request, "You do not have an order")
        return redirect("shop:cart")
        
@login_required
def remove_from_cart(request, id):
    product = get_object_or_404(Product, id=id)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        
        if order.products.filter(product_id=id).exists():
            order_item = OrderItem.objects.filter(
                product = product,
                user = request.user,
                ordered = False
            )[0]
            order_item.delete()
            messages.info(request, "Product removed from cart successfully")
            return redirect("shop:cart")
        
        else:
            messages.info(request, "This Product is not in your cart")
            return redirect("shop: product", id=id)
        
    else:
        messages.info(request, "You do not have an order")
        return redirect("shop: product", id=id)
    
@login_required
def order_summary(request):
    categories = Category.objects.all()

    try:
        order = Order.objects.get(user=request.user, ordered=False)

        return render(request, 'cart.html', {'order': order,
                                             'categories': categories})
    
    except ObjectDoesNotExist:
        messages.info(request, "You do not have an order")
        return redirect('shop:home')

@login_required
def checkout_view(request):
    categories = Category.objects.all()
    try:
        order = Order.objects.get(user=request.user, ordered=False)

        if request.method == "POST":
            form = CheckoutForm(request.POST)

            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                city = form.cleaned_data.get('city')
                zip = form.cleaned_data.get('zip')

                checkout_address, created = Checkout.objects.get_or_create(
                    user=request.user,
                    order=order,
                    

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="hero-section position-relative bg-light-blue padding-medium">
    <div class="hero-content">
      <div class="container">
        <div class="row">
          <div class="text-center padding-large no-padding-bottom">
            <h1 class="display-2 text-uppercase text-dark">Login</h1>
            <div class="breadcrumbs">
              <span class="item">
                <a href="{% url 'shop:home' %}">Home &gt;</a>
              </span>
              <span class="item">Login</span>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>


<div class="contact-us padding-large">
    <div class="container">
        <div class="row">
            <!--
            <div class="contact-info col-lg-6 pb-3">
            <h2 class="display-7 text-uppercase text-dark">Contact info</h2>
            <p>Tortor dignissim convallis aenean et tortor at risus viverra adipiscing.</p>
            <div class="page-content d-flex flex-wrap">
                <div class="col-lg-6 col-sm-12">
                <div class="content-box text-dark pe-4 mb-5">
                    <h3 class="card-title text-uppercase text-decoration-underline">Office</h3>
                    <div class="contact-address pt-3">
                    <p>730 Glenstone Ave 65802, Springfield, US</p>
                    </div>
                    <div class="contact-number">
                    <p>
                        <a href="#">+123 987 321</a>
                    </p>
                    <p>
                        <a href="#">+123 123 654</a>
                    </p>
                    </div>
                    <div class="email-address">
                    <p>
                        <a href="#">ministore@yourinfo.com</a>
                    </p>
                    </div>
                </div>
                </div>
                <div class="col-lg-6 col-sm-12">
                <div class="content-box">
                    <h3 class="card-title text-uppercase text-decoration-underline">Management</h3>
                    <div class="contact-address pt-3">
                    <p>730 Glenstone Ave 65802, Springfield, US</p>
                    </div>
                    <div class="contact-number">
                    <p>
                        <a href="#">+123 987 321</a>
                    </p>
                    <p>
                        <a href="#">+123 123 654</a>
                    </p>
                    </div>
                    <div class="email-address">
                    <p>
                        <a href="#">ministore@yourinfo.com</a>
                    </p>
                    </div>
                </div>
                </div>
            </div>
            </div>
            -->

            <div class="col-lg-6">
                <h2 class="display-7 text-uppercase text-dark pb-4">Welcome Back!</h2>
                <p>Welcome to Get Energy, your trusted partner in the pursuit of renewable energy solutions.</p>

                {% for message in messages %}
                    <div class="container-fluid p-0">
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                        <!--
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="True">&times;</span>
                        </button>
                        -->
                        {{ message }}
                        </div>
                    </div>
                {% endfor %}

                <div class="billing-details">
                    <form method="POST">
                        {% csrf_token %}
                        <label for="username">Username*</label>
                        <input type="text" id="username" name="username" class="form-control mt-2 mb-4 ps-3">
                        <label for="password">Password*</label>
                        <input type="password" id="password" name="password" class="form-control mt-2 mb-4 ps-3">
                        <button type="submit" class="btn btn-dark btn-medium text-uppercase btn-rounded">Submit</button>
                    </form>
                    
                </div>
                

                <p class="pt-4 pb-4">Don't have an account <a href="{% url 'shop:register_page' %}">sign up</a></p>

              </div>
        </div>
    </div>
</div>




{% endblock content %}

templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id="billboard" class="position-relative overflow-hidden bg-light-blue">
    <div class="swiper main-swiper">
        <div class="swiper-wrapper">
  
          {% for company in companies %}
          <div class="swiper-slide" style="background: url({{ company.cover_photo.url }}); height: 500px; padding-top: 10%; -bottom: 10%">
            <div class="container">
              <div class="row d-flex align-items-center">
                <div class="col-md-6">
                  <div class="banner-content">
                    <h1 class="display-2 text-uppercase text-light pb-5" style="font-weight: 400">{{ company.name }}</h1>
                    <a href="{% url 'shop:company-shop' company.id 1 %}" class="btn btn-medium btn-dark text-uppercase btn-rounded-none">Shop Product</a>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="image-holder">
                    
                    <img src="" alt="banner">
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
      <div class="swiper-icon swiper-arrow swiper-arrow-prev">
        <svg class="chevron-left">
          <use xlink:href="#chevron-left" />
        </svg>
      </div>
      <div class="swiper-icon swiper-arrow swiper-arrow-next">
        <svg class="chevron-right">
          <use xlink:href="#chevron-right" />
        </svg>
      </div>
</section>



<div class="shopify-grid padding-large">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="filter-shop d-flex justify-content-between">
                <div class="showing-product">
                    <p>Showing 1–9 of 55 results</p>
                </div>
                <div class="sort-by">
                    <select id="input-sort" class="form-control" data-filter-sort="" data-filter-order="">
                    <option value="">Default sorting</option>
                    <option value="">Name (A - Z)</option>
                    <option value="">Name (Z - A)</option>
                    <option value="">Price (Low-High)</option>
                    <option value="">Price (High-Low)</option>
                    <option value="">Rating (Highest)</option>
                    <option value="">Rating (Lowest)</option>
                    <option value="">Model (A - Z)</option>
                    <option value="">Model (Z - A)</option>   
                    </select>
                </div>
                </div>

                <div class="product-content product-store d-flex justify-content-between flex-wrap">
                    {% for product in products %}

                    <div class="col-lg-4 col-md-6">
                        <div class="product-card position-relative pe-3 pb-3">
                        <div class="image-holder1 image-holder">
                            <img src="{{ product.photo.url }}" alt="product-item" class="img-fluid">
                        </div>
                        <div class="cart-concern position-absolute">
                            <div class="cart-button d-flex">
                            <div class="btn-left">
                                <a href="{{ product.get_add_to_cart_url }}" class="btn btn-medium btn-black">Add to Cart</a>
                                <svg class="cart-outline position-absolute">
                                <use xlink:href="#cart-outline"></use>
                                </svg>
                            </div>
                            </div>
                        </div>
                        <div class="card-detail d-flex justify-content-between pt-3 pb-3">
                            <h3 class="card-title text-uppercase">
                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </h3>
                            <span class="item-price text-primary">${{ product.price }}</span>
                        </div>
                        </div>                  
                    </div>
                    
                    {% endfor %}
                </div>

                <nav class="navigation paging-navigation text-center padding-medium" role="navigation">
                    <div class="pagination loop-pagination d-flex justify-content-center align-items-center">

                        {% block pagination %}

                            {% if products.has_previous %}
                                <a href="{% url 'shop:shop' products.previous_page_number %}">
                                    <svg class="chevron-left pe-3">
                                        <use xlink:href="#chevron-left"></use>
                                    </svg>
                                </a>
                            {% endif %}

                            {% for page_number in products.paginator.get_elided_page_range %}
                                <!--<span aria-current="page" class="page-numbers current pe-3">1</span> -->
                                {% if page_number == products.paginator.ELLIPSIS %}
                                    {{ page_number }}
                                {% else %}
                                    <a class="{% if page_number == product.number %} current {% endif %}page-numbers pe-3" href="{% url 'shop:shop' page_number %}">{{page_number}}</a>
                                {% endif %}
                            {% endfor %}

                            {% if products.has_next %}
                                <a href="{% url 'shop:shop' products.next_page_number %}">
                                    <svg class="chevron-right ps-3">
                                        <use xlink:href="#chevron-right"></use>
                                    </svg>
                                </a>
                            {% endif %}

                        {% endblock %}

                    </div>
                </nav>
            </main>

            <aside class="col-md-3">
                <div class="sidebar">
                <div class="widget-menu">
                    <div class="widget-search-bar">
                    <form role="search" action="{% url 'shop:shop' 1 %}" method="get" class="d-flex">
                        <input class="search-field" placeholder="Search" name="search" type="search">
                        <button type="submit" class="search-icon bg-dark">
                            <svg class="search text-light">
                                <use xlink:href="#search"></use>
                            </svg>
                        </button>
                    </form>
                    </div> 
                </div>
                <div class="widget-product-categories pt-5">
                    <h5 class="widget-title text-decoration-underline text-uppercase">Categories</h5>
                    <ul class="product-categories sidebar-list list-unstyled">
                    <li class="cat-item">
                        <a href="/collections/categories">All</a>
                    </li>
                    {% for cat in categories %}
                    <li class="cat-item">
                        <a href="{% url 'shop:shop-cat' cat.name 1 %}">{{ cat.name }}</a>
                    </li>
                    {% endfor %}
                    
                    </ul>
                </div>

                <!--
                    <div class="widget-product-tags pt-3">
                        <h5 class="widget-title text-decoration-underline text-uppercase">Tags</h5>
                        <ul class="product-tags sidebar-list list-unstyled">
                        <li class="tags-item">
                            <a href="">White</a>
                        </li>
                        <li class="tags-item">
                            <a href="">Cheap</a>
                        </li>
                        <li class="tags-item">
                            <a href="">Mobile</a>
                        </li>
                        <li class="tags-item">
                            <a href="">Modern</a>
                        </li>
                        </ul>
                    </div>
                    <div class="widget-product-brands pt-3">
                        <h5 class="widget-title text-decoration-underline text-uppercase">Brands</h5>
                        <ul class="product-tags sidebar-list list-unstyled">
                        <li class="tags-item">
                            <a href="">Apple</a>
                        </li>
                        <li class="tags-item">
                            <a href="">Samsung</a>
                        </li>
                        <li class="tags-item">
                            <a href="">Huwai</a>
                        </li>
                        </ul>
                    </div>
                    <div class="widget-price-filter pt-3">
                        <h5 class="widget-titlewidget-title text-decoration-underline text-uppercase">Filter By Price</h5>
                        <ul class="product-tags sidebar-list list-unstyled">
                        <li class="tags-item">
                            <a href="">Less than $10</a>
                        </li>
                        <li class="tags-item">
                            <a href="">$10- $20</a>
                        </li>
                        <li class="tags-item">
                            <a href="">$20- $30</a>
                        </li>
                        <li class="tags-item">
                            <a href="">$30- $40</a>
                        </li>
                        <li class="tags-item">
                            <a href="">$40- $50</a>
                        </li>
                        </ul>
                    </div>
                    </div>
                -->

            </aside>

        </div>
    </div>
</div>


{% endblock  %}