ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('payments/', include('payment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('success/', views.payment_success, name='success'),
    path('canceled', views.payment_canceled, name='canceled')
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth

app_name = 'shop'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('shop/<int:page>', views.shop, name='shop'),
    path('shop/<name>/<int:page>/', views.shop_cat, name='shop-cat'),
    path('company/<int:id>/<int:page>/', views.company_shop, name='company-shop'),
    path('product/<int:id>/', views.product, name='product'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove-from-cart'),
    path('reduce-order-quantity/<int:id>/', views.reduce_order_quantity, name='reduce-order-quantity'),
    path('cart/', views.order_summary, name='cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('accounts/login/', views.login_view, name='login_page'),
    path('register/', views.register_view, name='register_page'),
    path('logout/', views.logout_view, name='logout')
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payment/models.py
from django.db import models
from shop.models import Order

# Create your models here.

class Payment(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='payment')
    email = models.EmailField()
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    paystack_ref = models.CharField(max_length=100, blank=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Payment {self.id}"
    
    def get_amount(self):
        return self.amount
        

payment/views.py
from django.shortcuts import render
import json
import requests
from django.conf import settings
from django.shortcuts import get_object_or_404
from .models import Payment
from shop.models import Order
from django.urls import reverse
from django.shortcuts import redirect

# Create your views here.

api_key = settings.PAYSTACK_TEST_SECRET_KEY
url = settings.PAYSTACK_INITIALIZE_PAYMENT_URL


def payment_process(request):

    payment_id = request.session.get('payment_id')
    payment = get_object_or_404(Payment, id=payment_id)

    amount = payment.get_amount() * 100

    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:success"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))

        metadata = json.dumps({"payment_id": payment_id,
                               "cancel_action": cancel_url})
        
        session_data = {
            'email': payment.email,
            'amount': amount,
            'callback_url': success_url,
            'metadata': metadata
        }

        headers = {"authorization": f"Bearer {api_key}"}

        #Api request to paystack server
        r = requests.post(url, headers=headers, data=session_data)
        response = r.json()
        print(response)
        if response["status"] == True:
            #redirect to paystack payment form
            try:
                redirect_url = response['data']['authorization_url']
                return redirect(redirect_url, code=303)

            except:
                pass

        else:
            return render(request, 'payment/process.html', locals())
    
    else:
        return render(request, 'payment/process.html', locals())


def payment_success(request):

    payment_id = request.session.get('payment_id', None)
    payment = get_object_or_404(Payment, id=payment_id)
    order = payment.order

    ref = request.GET.get('reference', '')

    url = 'https://api.paystack.co/transaction/verify/{}'.format(ref)

    headers = {"authorization": f"Bearer {api_key}"}
    r = requests.get(url, headers=headers)
    res = r.json()
    res = res["data"]

    if res['status'] == 'success':
        payment.paystack_ref = ref
        payment.paid = True
        payment.save()
        
        order.ordered = True
        order.save()

    return render(request, 'payment/success.html', locals())


def payment_canceled(request):

    return render(request, 'payment/canceled.html')

templates/payment/canceled.html
{% extends "base.html" %}

{% block content%}
<div class="container mt-3">
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
</div>
{% endblock %}

templates/payment/process.html
{% extends "base.html" %}

{% block content%}

<section class="hero-section position-relative bg-light-blue padding-medium">
    <div class="hero-content">
      <div class="container">
        <div class="row">
          <div class="text-center padding-large no-padding-bottom">
            <h1 class="display-2 text-uppercase text-dark">Payment {{ payment.id }}</h1>
            <div class="breadcrumbs">
              <span class="item">
                <a href="{% url 'shop:shop' 1 %}">Home &gt;</a>
              </span>
              <span class="item">payment</span>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<div class="container mt-5">
    
    <table class="table">
        <tr>
            <th>Created</th>
            <td>{{ payment.created_on }}</td>
        </tr>
        <tr>
            <th>Customer</th>
            <td>{{ payment.order.user.first_name }} {{ payment.order.user.last_name }}</td>
        </tr>
        <tr>
            <th>E-mail</th>
            <td><a href="mailto:{{ payment.email }}">{{ payment.email }}</a></td>
        </tr>
        <tr>
            <th>City</th>
            <td>
                {{ payment.order.checkout.city }}
            </td>
        </tr>
        <tr>
            <th>Total amount</th>
            <td>${{ payment.get_amount }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{% if payment.paid %}Paid{% else %}Pending payment{% endif %}</td>
        </tr>
        <tr>
            <th>Paystack payment</th>
            <td>
                {% if payment.paystack_ref %}
                    ##################
                {% endif %}
            </td>
        </tr>

        
    </table>

    <table class="table">
        <tr>
            <th>
                <form action="{% url "payment:process" %}" method="POST">
                    <input type="submit" class="btn btn-primary" value="Pay now">
                    {% csrf_token %}
                </form>
            </th>

            <td>
                <a href="#" onclick="window.print();">
                    Print payment
                </a>
            </td>
        </tr>
    </table>

   
</div>
{% endblock %}

templates/payment/success.html
{% extends "base.html" %}

{% block content%}

<section class="hero-section position-relative bg-light-blue padding-medium">
    <div class="hero-content">
      <div class="container">
        <div class="row">
          <div class="text-center padding-large no-padding-bottom">
            <h1 class="display-2 text-uppercase text-dark">Payment {{ payment.id }}</h1>
            <div class="breadcrumbs">
              <span class="item">
                <a href="{% url 'shop:shop' 1 %}">Home &gt;</a>
              </span>
              <span class="item">payment</span>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<div class="container mt-3">
    <h1>Your payment was successful</h1>
    <p>Your payment has been processed successfully.</p>
</div>
{% endblock %}